version: "3"
services:
  db: 
    image: onjin/alpine-postgres
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
  server:
    build:
      context: ./backend
    env_file: ./backend/.env
    environment:
      - FRONTEND_PORT=${FRONTEND_PORT}
    user: "node:node"
    depends_on:
      - db
    ports:
      - "${BACKEND_PORT}:80"
    volumes:
    - ./uploads:/home/node/app/uploads
  frontend:
    build:
      context: ./frontend
    env_file: ./frontend/.env.production.local
    ports:
      - "${FRONTEND_PORT}:80"
