version: "3"
services:
  db: 
    image: onjin/alpine-postgres
    container_name: postgres_dev
    environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    - POSTGRES_USER=${POSTGRES_USER}
    - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5437:5432
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
  server:
    build:
      context: ./backend
    env_file: ./backend/.env
    user: "node:node"
    depends_on:
      - db
    ports:
      - 8086:8085
    volumes:
    - ./uploads:/home/node/app/uploads
  frontend:
    build:
      context: ./frontend
    env_file: ./frontend/.env.production.local
    ports:
      - 8080:80